# Generated by Django 5.0 on 2024-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0003_data_comment_data_is_liked_data_num_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='num_likes',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
