# Generated by Django 5.0 on 2024-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0004_alter_data_num_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='num_likes',
            field=models.PositiveIntegerField(default=0, max_length=5),
        ),
    ]
