# Generated by Django 5.0 on 2024-10-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='comment',
        ),
        migrations.AddField(
            model_name='data',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
